---
- name: Pull docker image of ToDoList
  hosts: all
  tasks:
    - name: Pull calculator devops image
      docker_image:
        name: sanchitdwivedi/calculator:latest
        source: pull
        
    - name: deploy calculator docker container
      docker_container:
        image: sanchitdwivedi/calculator:latest
        name: calculator
        state: started
        ports:
          - "3000:80"
...
