---
- name: Pull docker image of ToDoList
  hosts: all
  tasks:
    - name: Pull calculator devops image
      docker_image:
        name: sanchitdwivedi/calculator:latest
        source: pull

- name: Run Docker Image
  hosts: all
  tasks:
    - name: deploy calculator docker container
      docker_container:
        image: sanchitdwivedi/calculator:latest
        name: calculator
        state: started
        auto_remove: true
        ports:
          - "3000:80"
...
