---
- hosts: dev
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Start the container
      docker_container:
        name: calculator
        image: "sanchitdwivedi/calculator:843c372"
        state: started
        published_ports:
          - 0.0.0.0:4200:4200
